version: "3.3"

services:
  database:
    container_name: t10challenge_database
    image: postgres
    restart: aways
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=t10challenge
      - POSTGRES_USER=t10challenge
    ports:
      - 5434:5432